import Image from "next/image";
import styles from "./page.module.css";
import Flashcard from "./components/Flashcard";
import "./page.css";

export default function Home() {
  return (
    <div className="background">
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
      <Flashcard
        chineseCharacter="你"
        pinyin="nǐ"
        englishTranslation="you"
        indonesianTranslation="kamu"
      />
    </div>
  );
}
